import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { DeferredScripts } from "@/components/deferred-scripts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    other: [
      {
        rel: "preload",
        url: "/Images/hero.png",
        type: "image/png",
        fetchPriority: "high",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="lenis lenis-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-zinc-950 bg-noise text-zinc-300 antialiased`}
      >
        <DeferredScripts />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
